version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: vvakame/circleci-gaego
    steps:
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run: npm install -g yarn
      - run: ./setup.sh
      # caching
      - save_cache:
          # Circle CI 2.0のキャッシュは一度生成すると破棄が難しく、一度キャッシュが作られると次回以降のsave_cacheが無視される
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            # OS毎に場所が違う yarn cache dir で調べる
            - /usr/local/share/.cache/yarn/v1
      - run: npm run build
      - run:
          name: Setup GCP authorization
          command: |
            echo $GOOGLE_OAUTH_JSON | base64 --decode > gcp-authorization.json
            gcloud auth activate-service-account --key-file gcp-authorization.json
      - run: ./docker-build.sh
      - deploy:
          name: Deploy to GKE
          command: |
            case "${CIRCLE_BRANCH}" in
              "master" ) ./deploy.sh ;;
            esac
          working_directory: ./api

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
