apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blog-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: blog-deployment
  minReplicas: 1
  maxReplicas: 2
